FROM node:22-alpine AS dependencies

WORKDIR /app

COPY package*.json ./

RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi


FROM node:22-alpine AS development

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=<FRONTEND_PORT>
ENV HOSTNAME=0.0.0.0

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

EXPOSE <FRONTEND_PORT>

CMD ["npm", "run", "dev"]


FROM node:22-alpine AS builder

WORKDIR /app

ARG MODE=prod
ARG NEXT_PUBLIC_SITE=<PUBLIC_FRONTEND_URL>
ARG NEXT_PUBLIC_API_URL=<PUBLIC_API_URL>

ENV MODE=$MODE
ENV NEXT_PUBLIC_SITE=$NEXT_PUBLIC_SITE
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

RUN npm run build


FROM node:22-alpine AS production

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=<FRONTEND_PORT>
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE <FRONTEND_PORT>

CMD ["node", "server.js"]
